CREATE TABLE car (
   car_uid UUID NOT NULL DEFAULT ( gen_random_uuid() ),
   make VARCHAR,
   model VARCHAR,
   price NUMERIC(19,2) NOT NULL CHECK (price > 0),

   PRIMARY KEY (car_uid)
);
CREATE TABLE person (
    -- desire: ability to insert (custom uid),   
    --         ability to generate automatically
    --         ability to check correct form based on regex
    --         not null
    -- method: generated by default as () stored
    --         NOT NULL DEFAULT (default_expr) CHECK ( expression )
    -- insertion of custom uuids is allowed (essentially a GENERATED BY DEFAULT)
    person_uid UUID NOT NULL DEFAULT ( gen_random_uuid() ),
    first_name VARCHAR NOT NULL,
    last_name VARCHAR NOT NULL,
    gender VARCHAR NOT NULL,
    email VARCHAR,
    date_of_birth VARCHAR NOT NULL,
    country_of_birth VARCHAR NOT NULL,
    car_uid UUID,
    FOREIGN KEY (car_uid) REFERENCES car (car_uid),
    UNIQUE(car_uid, email), -- (car_uid) one to one | one to none

    PRIMARY KEY (person_uid)
);


insert into person values (default, 'Fernanda', 'Beardon', 'Female', 'fernandab@is.gd', '1953-10-28', 'Comoros');
insert into person values (default, 'Omar', 'Colmore', 'Male', null, '1921-04-03', 'Finland');
insert into person values (default, 'John', 'Matuschek', 'Male', 'john@feedburner.com', '1965-02-28', 'England');

insert into car values (default, 'GMC', 'Acadia', '17662.69');
insert into car values (default, 'Land Rover', 'Sterling', '87665.38');