
create table car (
	-- Identity should be used over serial types, as it is
	-- 		part of the sql standard
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- by default, as id is included in mock data insertions
	make text NOT NULL, -- better for storage
	model text NOT NULL, -- better for storage
	price numeric(19,2) NOT NULL -- end column should have no comma
);